pucts = ['!', '@', '#', '.', ':', ',', '$', '&', '%', '$', '~', "'", '+', '=', '*', '^', '>', '<', ';', '``']

numbers = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
                'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty',
                'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred', 'Thousand', 'million',
                'billion']

suffixes = {'s', 'y', 'ic', 'er', 'ly', 'en', 'or', 'fy', 'ar', 'an', 'es', 'ed', 'cy', 'ia', 'al', 'ty', 'ify', 'ure',
            'ics', 'ite', 'ply', 'sue', 'dit', 'gen', 'dox', 'act', 'ity', 'ist', 'nym', 'log', 'ies', 'ing', 'art',
            'ade', 'mit', 'pod', 'ate', 'pel', 'ver', 'ish', 'ice', 'ive', 'mal', 'age', 'fer', 'ian', 'acy', 'ory',
            'ier', 'ose', 'ial', 'ion', 'est', 'tem', 'ful', 'ery', 'ess', 'ism', 'ous', 'nox', 'ent', 'ard', 'fix',
            'cur', 'ile', 'ary', 'ize', 'ant', 'tact', 'pute', 'tent', 'ancy', 'less', 'ward', 'vert', 'duct', 'pict',
            'eous', 'port', 'cept', 'ceed', 'fuge', 'voke', 'cord', 'pend', 'glot', 'iest', 'sper', 'volt', 'fect',
            'ious', 'with', 'cosm', 'rupt', 'sent', 'vict', 'ible', 'flex', 'form', 'fess', 'gest', 'quip', 'ness',
            'sist', 'tect', 'wise', 'tire', 'gram', 'crat', 'vent', 'main', 'able', 'mand', 'fold', 'pair', 'ical',
            'lect', 'ship', 'sect', 'here', 'gree', 'thet', 'stry', 'sign', 'tend', 'onym', 'ance', 'ency', 'hale',
            'lide', 'sess', 'ient', 'flux', 'cede', 'ment', 'pare', 'tort', 'dict', 'tain', 'cade', 'fort', 'cide',
            'just', 'vade', 'ence', 'sume', 'test', 'cuse', 'ster', 'fuse', 'cort', 'ject', 'lude', 'join', 'cracy',
            'itive', 'plore', 'scope', 'ation', 'gress', 'fract', 'flect', 'drome', 'cause', 'tract', 'ative', 'mania',
            'gnant', 'spect', 'meter', 'graph', 'pound', 'sanct', 'belli', 'flict', 'ology', 'stroy', 'phage', 'pathy',
            'iatry', 'labor', 'claim', 'struct', 'crease', 'sphere', 'judice', 'strict', 'phobia', 'strain', 'script',
            'thesis', 'tribute', 'portion'}

prefixes = {'e', 'a', 'zo', 'ob', 'ag', 'bi', 'as', 'an', 'in', 'ir', 'fa', 'dy', 'af', 'di', 'ec', 'oc', 'em', 'en',
            'op', 'at', 'im', 'de', 'st', 'ev', 'ab', 'al', 'il', 'ex', 'ap', 'of', 'un', 'be', 'vi', 'et', 'ad', 'se',
            'ri', 're', 'ac', 'am', 'co', 'ply', 'pop', 'erg', 'auc', 'col', 'cad', 'ses', 'man', 'tri', 'fid', 'ann',
            'aqu', 'dis', 'the', 'sus', 'ver', 'fas', 'aer', 'hes', 'cap', 'div', 'con', 'sym', 'fer', 'reg', 'flu',
            'ami', 'suc', 'tem', 'lun', 'geo', 'mem', 'bar', 'ana', 'aur', 'alb', 'pot', 'vac', 'sed', 'dic', 'fin',
            'syn', 'ang', 'fig', 'pod', 'suf', 'neo', 'typ', 'loc', 'vic', 'her', 'ven', 'fea', 'aph', 'mal', 'ped',
            'pre', 'acu', 'don', 'nov', 'vor', 'dif', 'dia', 'phe', 'mar', 'glu', 'abs', 'mis', 'nai', 'ten', 'ant',
            'gin', 'hum', 'lot', 'gen', 'act', 'mer', 'tra', 'cas', 'mon', 'nom', 'leg', 'log', 'mob', 'eco', 'cit',
            'vol', 'sol', 'pan', 'cat', 'nat', 'mor', 'sex', 'com', 'doc', 'for', 'aud', 'aug', 'fix', 'cur', 'fac',
            'vis', 'veh', 'non', 'oct', 'apo', 'alt', 'viv', 'pac', 'sec', 'tox', 'agi', 'sen', 'min', 'dox', 'aus',
            'dys', 'noc', 'cor', 'lum', 'sub', 'tor', 'sup', 'ano', 'sci', 'dem', 'lav', 'cre', 'fan', 'sat', 'uni',
            'epi', 'sur', 'pat', 'per', 'pos', 'civ', 'vid', 'sta', 'ali', 'cog', 'lau', 'dec', 'hex', 'fic', 'plu',
            'bio', 'mot', 'end', 'teg', 'dei', 'aut', 'pro', 'voc', 'lus', 'tact', 'pict', 'grat', 'macr', 'greg',
            'soci', 'amor', 'hydr', 'hemo', 'salv', 'cycl', 'acer', 'tang', 'pico', 'carn', 'heal', 'crit', 'nano',
            'salu', 'ridi', 'mari', 'tend', 'risi', 'stat', 'andr', 'plus', 'grav', 'meso', 'anti', 'phon', 'vers',
            'loco', 'bibl', 'tele', 'stru', 'sequ', 'prin', 'lust', 'leag', 'caus', 'cour', 'poli', 'plur', 'dura',
            'pend', 'trib', 'sens', 'homo', 'ambi', 'cosm', 'form', 'metr', 'mono', 'coll', 'tera', 'patr', 'nasc',
            'fluc', 'over', 'allo', 'vent', 'main', 'cent', 'mand', 'tors', 'path', 'fila', 'derm', 'sanc', 'neur',
            'sign', 'solv', 'sess', 'verv', 'arch', 'phil', 'veri', 'tort', 'corp', 'meta', 'vivi', 'fals', 'fort',
            'mort', 'mega', 'fact', 'magn', 'test', 'oper', 'valu', 'logo', 'medi', 'quad', 'aero', 'frag', 'terr',
            'phan', 'pass', 'loqu', 'grad', 'stan', 'rupt', 'puls', 'term', 'sent', 'fain', 'gest', 'doct', 'agro',
            'plac', 'gram', 'fide', 'capt', 'demo', 'hypn', 'vita', 'sump', 'ecto', 'theo', 'sect', 'acid', 'ante',
            'sept', 'prim', 'annu', 'germ', 'curs', 'post', 'kilo', 'cogn', 'pens', 'cred', 'dorm', 'dict', 'phot',
            'frai', 'caut', 'sacr', 'audi', 'omni', 'poly', 'miss', 'tens', 'fall', 'somn', 'equi', 'vert', 'crea',
            'para', 'port', 'soph', 'cord', 'mill', 'spir', 'with', 'auto', 'vict', 'peri', 'flex', 'cura', 'fore',
            'fili', 'vect', 'fant', 'deca', 'semi', 'here', 'bene', 'vali', 'astr', 'clam', 'solu', 'levi', 'manu',
            'giga', 'quer', 'acri', 'spec', 'brev', 'agri', 'ment', 'cath', 'dent', 'verb', 'anim', 'cata', 'cort',
            'serv', 'hydra', 'liber', 'fract', 'paleo', 'trans', 'multi', 'simul', 'extra', 'extro', 'feder', 'super',
            'andro', 'sanct', 'belli', 'quest', 'penta', 'punct', 'recti', 'supra', 'domin', 'morph', 'solut', 'simil',
            'phant', 'chrom', 'helio', 'ortho', 'cresc', 'spect', 'meter', 'quint', 'milli', 'signi', 'prime', 'aster',
            'intro', 'tempo', 'ambul', 'chron', 'exter', 'hyper', 'calor', 'femto', 'alter', 'tract', 'gastr', 'psych',
            'intra', 'mania', 'nomin', 'liter', 'photo', 'graph', 'retro', 'migra', 'infra', 'centr', 'labor', 'cyclo',
            'contr', 'nomen', 'numer', 'vicis', 'proto', 'therm', 'junct', 'scrib', 'terra', 'pater', 'juven', 'matri',
            'bibli', 'inter', 'dynam', 'micro', 'oligo', 'feign', 'human', 'hydro', 'capit', 'gloss', 'satis', 'struct',
            'biblio', 'contra', 'gastro', 'pneuma', 'string', 'ultima', 'phobia', 'sphere', 'hetero', 'volcan',
            'strict', 'centri', 'circum', 'numisma', 'pneumon', 'phlegma', 'counter', 'anthrop', 'portion'}

simple_past = {'bred', 'premade', 'told', 'repaid', 'laded', 'undershot', 'showed', 'unheld', 'outshined', 'resewed',
               'knitted', 'leaped', 'rewedded', 'retaught', 'staved', 'made', 'hewed', 'slinked', 'begot', 'relaid',
               'brought', 'reawoke', 'wore', 'daydreamt', 'miswedded', 'outthrew', 'overfed', 'interwound', 'outslept',
               'froze', 'was,', 'slept', 'went', 'smelt', 'predid', 'began', 'jerry-built', 'sneaked', 'lost', 'shined',
               'unbore', 'hamstrung', 'stall-fed', 'fell', 'sunburned', 'leapt', 'misled', 'begat', 'saw', 'dighted',
               'throve', 'clothed', 'swept', 'paid', 'heaved', 'strewed', 'led', 'taught', 'rebroadcasted', 'hagrode',
               'fed', 'retrofitted', 'rethought', 'flew', 'dared', 'wrote', 'shoed', 'test-drove', 'sought', 'flung',
               'dealt', 'undrew', 'wrung', 'rewore', 'interweaved', 'misspent', 'relearned', 'unbound', 'resold',
               'retore', 'reknitted', 'sunburnt', 'rang', 'overwore', 'dwelled', 'learned', 'blew', 'bore', 'unleaded',
               'misdealt', 'outwore', 'vext', 'unsaid', 'backslid', 'gilt', 'threw', 'trod', 'foretold', 'overbought',
               'mistaught', 'shrank', 'unwove', 'unhid', 'sank', 'gilded', 'slayed', 'bit', 'outbred', 'speeded',
               'stripped', 'unbent', 'pleaded', 'leant', 'stuck', 'outdrew', 'spelled', 'outwound', 'overspilled',
               'oversprang', 'drove', 'unsewed', 'quick-froze', 'gave', 'snuck', 'relayed', 'swore', 'drew', 'rewon',
               'rewound', 'proved', 'overdid', 'rove', 'self-fed', 'spat', 'overstood', 'foreknew', 'reran',
               'outsprung', 'hung', 'spoilt', 'stood', 'forgave', 'beseeched', 'broke', 'alit', 'misheard', 'slung',
               'lied', 'retook', 'fled', 'durst', 'rewaked', 'shod', 'bent', 'mistook', 'stung', 'oversprung',
               'outshot', 'forewent', 'misspelt', 'bethought', 'slew', 'overwrote', 'colorbred', 'met', 'reeved',
               'grew', 'thrived', 'fordid', 'spelt', 'shitted', 'shrove', 'betook', 'mistold', 'hid', 'inputted',
               'untaught', 'sang', 'mislearnt', 'underlay', 'overspilt', 'unreeved', 'laid', 'unclothed', 'halterbroke',
               'wedded', 'enwound', 'smote', 'overthought', 'oversaw', 'rewrote', 'swelled', 'got', 'overdrew',
               'frostbit', 'outsmelt', 'underlaid', 'shaved', 'quitted', 'sweated', 'outgrew', 'betted', 'outspun',
               'understood', 'unlearned', 'unknitted', 'lighted', 'outdrove', 'unweaved', 'arose', 'left', 'hand-fed',
               'rewove', 'overspent', 'overthrew', 'ran', 'forespoke', 'befell', 'mowed', 'mislearned', 'fought',
               'lent', 'sewed', 'missent', 'underwent', 'came', 'test-flew', 'dived', 'kneeled', 'missaid', 'unclad',
               'bestrewed', 'whetted', 'unstrung', 'sped', 'overrode', 'sunk', 'interwove', 'spilt', 'outlaid',
               'strove', 'inbred', 'burned', 'waked', 'typewrote', 'did', 'held', 'prebuilt', 'overbore', 'preshrank',
               'outleapt', 'sprung', 'sent', 'oversowed', 'shrunk', 'rebound', 'miswore', 'rehung', 'abode', 'outran',
               'outsang', 'spilled', 'crossbred', 'spoon-fed', 'knelt', 'overcame', 'unrove', 'outfought', 'clad',
               'upheld', 'awoke', 'rewetted', 'inlaid', 'found', 'reweaved', 'unwound', 'overwound', 'presold', 'swam',
               'outleaped', 'unmade', 'clung', 'misswore', 'overbred', 'overbuilt', 'outspent', 'bade', 'stunk',
               'misspelled', 'bled', 'struck', 'smelled', 'landslid', 'swung', 'waylaid', 'clapped', 'outtold', 'sowed',
               'spent', 'unwrote', 'unswore', 'bound', 'shot', 'rode', 'underwrote', 'sprang', 'overstrewed',
               'misthought', 'outspoke', 'stove', 'troubleshot', 'learnt', 'bereft', 'outdid', 'drank', 'outshone',
               'dove', 'unslung', 'beheld', 'took', 'outrode', 'sold', 'misdid', 'overleaped', 'awakened', 'shone',
               'wound', 'said', 'overleapt', 'slid', 'inweaved', 'foresaw', 'felt', 'refitted', 'gainsaid', 'underfed',
               'rewoke', 'undid', 'chose', 'stript', 'dreamed', 'outdrank', 'tore', 'unbuilt', 'bought', 'unlaid',
               'bereaved', 'burnt', 'outswore', 'heard', 'stank', 'overate', 'overspun', 'chid', 'overdrank',
               'misbecame', 'abided', 'underbought', 'broadcasted', 'oversold', 'redid', 'underspent', 'meant', 'built',
               'partook', 'regrew', 'rebuilt', 'became', 'overspoke', 'resent', 'weaved', 'redealt', 'rended',
               'forbore', 'lit', 'dwelt', 'ground', 'relighted', 'overlaid', 'disproved', 'foreran', 'unfroze',
               'overtook', 'overslept', 'strung', 'outsat', 'overshot', 'alighted', 'unstuck', 'wept', 'spoiled',
               'retold', 'outwrote', 'interlaid', 'outthought', 'slunk', 'ate', 'forswore', 'withheld', 'outflew',
               'sheared', 'outswam', 'pled', 'kept', 'forgot', 'unhung', 'overhung', 'stole', 'besought', 'wove', 'sat',
               'self-sowed', 'reheard', 'shrived', 'thought', 'remade', 'caught', 'spoke', 'sawed', 'rose', 'outputted',
               'rent', 'mislaid', 'unladed', 'dug', 'hove', 'woke', 'fitted', 'withdrew', 'skywrote', 'backbit',
               'oversewed', 'outsmelled', 'spun', 'outlied', 'outsaw', 'outsped', 'strode', 'misspoke', 'overpaid',
               'shook', 'hanged', 'foreshowed', 'prepaid', 'wetted', 'daydreamed', 'dreamt', 'overheard', 'overstruck',
               'undertook', 'crept', 'withstood', 'unspun', 'overlay', 'relearnt', 'won', 'unthought', 'interbred',
               'rived', 'knew', 'relit', 'chided', 'forbade', 'reground', 'clapt', 'unlearnt', 'miswrote', 'leaned',
               'overstrode', 'busted', 'handwrote', 'strived', 'vexed', 'forsook', 'inwove', 'overran', 'outsold',
               'outsprang', 'redrew', 'underran', 'shat', 'lay', 'had', 'outstood', 'misunderstood', 'undersold'}

past_participle = {'bred', 'proven', 'backslidden', 'forborne', 'premade', 'overtaken', 'told', 'repaid', 'laded',
                   'rewaken', 'undershot', 'showed', 'unheld', 'unsewn', 'handwritten', 'outshined', 'resewed',
                   'bidden', 'knitted', 'leaped', 'rewedded', 'broken', 'retaught', 'staved', 'made', 'hewed',
                   'slinked', 'relaid', 'brought', 'laden', 'slain', 'outridden', 'daydreamt', 'miswedded', 'overfed',
                   'riven', 'interwound', 'given', 'outslept', 'overstrewn', 'outsworn', 'slept', 'smelt',
                   'jerry-built', 'sneaked', 'lost', 'shined', 'hamstrung', 'stall-fed', 'sunburned', 'leapt', 'torn',
                   'sworn', 'foreshown', 'misled', 'dighted', 'spoken', 'shorn', 'clothed', 'swollen', 'swept', 'paid',
                   'outsung', 'heaved', 'strewed', 'sewn', 'led', 'taught', 'regrown', 'rebroadcasted', 'written',
                   'fed', 'retrofitted', 'rethought', 'dared', 'disproven', 'unhidden', 'shoed', 'sought', 'flung',
                   'dealt', 'wrung', 'interweaved', 'sown', 'browbeaten', 'misspent', 'relearned', 'resewn', 'unbound',
                   'resold', 'driven', 'reknitted', 'sunburnt', 'foreseen', 'sawn', 'dwelled', 'learned', 'unleaded',
                   'misdealt', 'vext', 'outspoken', 'bestrewn', 'backslid', 'gilt', 'unsaid', 'seen', 'trod',
                   'foretold', 'overbought', 'mistaught', 'redrawn', 'been', 'shaken', 'gilded', 'outflown', 'slayed',
                   'outbred', 'speeded', 'stripped', 'unbent', 'pleaded', 'fallen', 'undone', 'preshrunk', 'leant',
                   'stuck', 'spelled', 'outwound', 'overworn', 'overspilled', 'unsewed', 'backbitten', 'snuck', 'shown',
                   'drawn', 'relayed', 'rewon', 'redone', 'rewound', 'proved', 'forgiven', 'thriven', 'hewn', 'rove',
                   'self-fed', 'spat', 'risen', 'overstood', 'taken', 'rung', 'outsprung', 'hung', 'spoilt', 'awoken',
                   'stood', 'beseeched', 'miswritten', 'alit', 'misheard', 'slung', 'lied', 'fled', 'durst', 'known',
                   'rewaked', 'reworn', 'shod', 'chidden', 'bent', 'stung', 'interwoven', 'oversprung', 'outgrown',
                   'overthrown', 'outshot', 'misspelt', 'bethought', 'colorbred', 'hagridden', 'met', 'woken', 'reeved',
                   'thrived', 'spelt', 'forespoken', 'shitted', 'mistold', 'inputted', 'forbidden', 'blown',
                   'forgotten', 'untaught', 'halterbroken', 'mislearnt', 'overspilt', 'unreeved', 'retorn', 'laid',
                   'unclothed', 'wedded', 'enwound', 'smote', 'unsworn', 'overthought', 'overborne', 'swelled', 'got',
                   'outsmelt', 'underlaid', 'shaved', 'quitted', 'sweated', 'betted', 'outspun', 'understood',
                   'unlearned', 'retaken', 'unknitted', 'lighted', 'unweaved', 'left', 'hand-fed', 'overspent',
                   'misspoken', 'mowed', 'mislearned', 'fought', 'quick-frozen', 'lent', 'sewed', 'missent', 'missworn',
                   'foreknown', 'grown', 'befallen', 'dived', 'frozen', 'kneeled', 'hidden', 'missaid', 'unclad',
                   'bestrewed', 'overspoken', 'strewn', 'whetted', 'unstrung', 'overridden', 'sped', 'undersold',
                   'sunk', 'overdone', 'spilt', 'begotten', 'outlaid', 'inbred', 'burned', 'waked', 'held', 'prebuilt',
                   'unborne', 'lain', 'outleapt', 'sprung', 'sent', 'oversowed', 'shrunk', 'sung', 'rebound', 'shriven',
                   'unwritten', 'rehung', 'undrawn', 'arisen', 'spilled', 'unladen', 'mistaken', 'crossbred',
                   'spoon-fed', 'knelt', 'bitten', 'unrove', 'outfought', 'beaten', 'overdrunk', 'clad', 'upheld',
                   'drunk', 'rewetted', 'inlaid', 'found', 'reweaved', 'unwound', 'overwound', 'rewoven', 'overwritten',
                   'presold', 'outleaped', 'test-flown', 'unmade', 'clung', 'unfrozen', 'overbred', 'trodden',
                   'overbuilt', 'worn', 'outspent', 'outdone', 'stunk', 'misspelled', 'bled', 'struck', 'begun',
                   'eaten', 'smelled', 'landslid', 'swung', 'waylaid', 'clapped', 'outtold', 'sowed', 'spent', 'bound',
                   'shot', 'overstrewed', 'misthought', 'chosen', 'forsaken', 'stove', 'skywritten', 'troubleshot',
                   'learnt', 'bereft', 'outshone', 'born', 'unslung', 'beheld', 'undergone', 'sold', 'overleaped',
                   'awakened', 'shone', 'wound', 'said', 'overleapt', 'slid', 'inweaved', 'felt', 'refitted',
                   'gainsaid', 'undertaken', 'underfed', 'forsworn', 'overstridden', 'stript', 'dreamed', 'unbuilt',
                   'reawaken', 'bought', 'unlaid', 'partaken', 'frostbitten', 'bereaved', 'burnt', 'overseen', 'heard',
                   'overspun', 'overdrawn', 'underbought', 'abided', 'broadcasted', 'oversold', 'outdrawn',
                   'underspent', 'fordone', 'meant', 'built', 'rebuilt', 'overborn', 'withdrawn', 'foregone', 'gone',
                   'resent', 'weaved', 'outworn', 'redealt', 'mown', 'rended', 'lit', 'dwelt', 'ground', 'stolen',
                   'relighted', 'betaken', 'overeaten', 'predone', 'overlaid', 'disproved', 'outwritten', 'borne',
                   'underlain', 'outdrunk', 'oversewn', 'overslept', 'test-driven', 'strung', 'outsat', 'overshot',
                   'alighted', 'unstuck', 'wept', 'outseen', 'spoiled', 'retold', 'slunk', 'interlaid', 'outthought',
                   'self-sown', 'withheld', 'smitten', 'outthrown', 'sheared', 'stricken', 'pled', 'shaven', 'kept',
                   'swum', 'rewritten', 'forgot', 'oversown', 'unhung', 'overhung', 'woven', 'besought', 'sat',
                   'inwoven', 'self-sowed', 'reheard', 'thought', 'remade', 'caught', 'sawed', 'outputted', 'rent',
                   'mislaid', 'unladed', 'dug', 'hove', 'typewritten', 'fitted', 'unwoven', 'misdone', 'oversewed',
                   'outsmelled', 'spun', 'done', 'outlied', 'misworn', 'outsped', 'overpaid', 'hanged', 'foreshowed',
                   'prepaid', 'wetted', 'flown', 'daydreamed', 'dreamt', 'overheard', 'overstruck', 'crept',
                   'withstood', 'unspun', 'relearnt', 'stridden', 'underwritten', 'won', 'unthought', 'ridden',
                   'interbred', 'outswum', 'rived', 'striven', 'relit', 'outdriven', 'chided', 'gotten', 'reground',
                   'clapt', 'unlearnt', 'leaned', 'busted', 'strived', 'unborn', 'vexed', 'outsold', 'thrown', 'shat',
                   'outstood', 'had', 'misunderstood', 'overlain'}

experiments = {
    'exp_1': {'word_ctag': 1,
              'suffix': 1,
              'prefix': 1,
              'pptag_ptag_ctag': 5,
              'ptag_ctag': 3,
              'ctag': 1,
              'pword_ctag': 3,
              'nword_ctag': 3,
              'len_word': 1,
              'upper_lower_number': 1,
              'punctuation_starts': 1,
              'punctuation': 1,
              'num_of_uppers': 1,
              'is_number': 1,
              'irregular_verb': 1}}
