pucts = ['!', '@', '#', '.', ':', ',', '$', '&', '%', '$', '~', "'", '+', '=', '*', '^', '>', '<', ';', '``']

numbers = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
                'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty',
                'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred', 'Thousand', 'million',
                'billion']

suffixes = {'y', 'ic', 'er', 'ly', 'en', 'or', 'fy', 'ar', 'an', 'es', 'ed', 'cy', 'ia', 'al', 'ty', 'ify', 'ure',
            'ics', 'ite', 'ply', 'sue', 'dit', 'gen', 'dox', 'act', 'ity', 'ist', 'nym', 'log', 'ies', 'ing', 'art',
            'ade', 'mit', 'pod', 'ate', 'pel', 'ver', 'ish', 'ice', 'ive', 'mal', 'age', 'fer', 'ian', 'acy', 'ory',
            'ier', 'ose', 'ial', 'ion', 'est', 'tem', 'ful', 'ery', 'ess', 'ism', 'ous', 'nox', 'ent', 'ard', 'fix',
            'cur', 'ile', 'ary', 'ize', 'ant', 'tact', 'pute', 'tent', 'ancy', 'less', 'ward', 'vert', 'duct', 'pict',
            'eous', 'port', 'cept', 'ceed', 'fuge', 'voke', 'cord', 'pend', 'glot', 'iest', 'sper', 'volt', 'fect',
            'ious', 'with', 'cosm', 'rupt', 'sent', 'vict', 'ible', 'flex', 'form', 'fess', 'gest', 'quip', 'ness',
            'sist', 'tect', 'wise', 'tire', 'gram', 'crat', 'vent', 'main', 'able', 'mand', 'fold', 'pair', 'ical',
            'lect', 'ship', 'sect', 'here', 'gree', 'thet', 'stry', 'sign', 'tend', 'onym', 'ance', 'ency', 'hale',
            'lide', 'sess', 'ient', 'flux', 'cede', 'ment', 'pare', 'tort', 'dict', 'tain', 'cade', 'fort', 'cide',
            'just', 'vade', 'ence', 'sume', 'test', 'cuse', 'ster', 'fuse', 'cort', 'ject', 'lude', 'join', 'cracy',
            'itive', 'plore', 'scope', 'ation', 'gress', 'fract', 'flect', 'drome', 'cause', 'tract', 'ative', 'mania',
            'gnant', 'spect', 'meter', 'graph', 'pound', 'sanct', 'belli', 'flict', 'ology', 'stroy', 'phage', 'pathy',
            'iatry', 'labor', 'claim', 'struct', 'crease', 'sphere', 'judice', 'strict', 'phobia', 'strain', 'script',
            'thesis', 'tribute', 'portion'}

prefixes = {'e', 'a', 'zo', 'ob', 'ag', 'bi', 'as', 'an', 'in', 'ir', 'fa', 'dy', 'af', 'di', 'ec', 'oc', 'em', 'en',
            'op', 'at', 'im', 'de', 'st', 'ev', 'ab', 'al', 'il', 'ex', 'ap', 'of', 'un', 'be', 'vi', 'et', 'ad', 'se',
            'ri', 're', 'ac', 'am', 'co', 'ply', 'pop', 'erg', 'auc', 'col', 'cad', 'ses', 'man', 'tri', 'fid', 'ann',
            'aqu', 'dis', 'the', 'sus', 'ver', 'fas', 'aer', 'hes', 'cap', 'div', 'con', 'sym', 'fer', 'reg', 'flu',
            'ami', 'suc', 'tem', 'lun', 'geo', 'mem', 'bar', 'ana', 'aur', 'alb', 'pot', 'vac', 'sed', 'dic', 'fin',
            'syn', 'ang', 'fig', 'pod', 'suf', 'neo', 'typ', 'loc', 'vic', 'her', 'ven', 'fea', 'aph', 'mal', 'ped',
            'pre', 'acu', 'don', 'nov', 'vor', 'dif', 'dia', 'phe', 'mar', 'glu', 'abs', 'mis', 'nai', 'ten', 'ant',
            'gin', 'hum', 'lot', 'gen', 'act', 'mer', 'tra', 'cas', 'mon', 'nom', 'leg', 'log', 'mob', 'eco', 'cit',
            'vol', 'sol', 'pan', 'cat', 'nat', 'mor', 'sex', 'com', 'doc', 'for', 'aud', 'aug', 'fix', 'cur', 'fac',
            'vis', 'veh', 'non', 'oct', 'apo', 'alt', 'viv', 'pac', 'sec', 'tox', 'agi', 'sen', 'min', 'dox', 'aus',
            'dys', 'noc', 'cor', 'lum', 'sub', 'tor', 'sup', 'ano', 'sci', 'dem', 'lav', 'cre', 'fan', 'sat', 'uni',
            'epi', 'sur', 'pat', 'per', 'pos', 'civ', 'vid', 'sta', 'ali', 'cog', 'lau', 'dec', 'hex', 'fic', 'plu',
            'bio', 'mot', 'end', 'teg', 'dei', 'aut', 'pro', 'voc', 'lus', 'tact', 'pict', 'grat', 'macr', 'greg',
            'soci', 'amor', 'hydr', 'hemo', 'salv', 'cycl', 'acer', 'tang', 'pico', 'carn', 'heal', 'crit', 'nano',
            'salu', 'ridi', 'mari', 'tend', 'risi', 'stat', 'andr', 'plus', 'grav', 'meso', 'anti', 'phon', 'vers',
            'loco', 'bibl', 'tele', 'stru', 'sequ', 'prin', 'lust', 'leag', 'caus', 'cour', 'poli', 'plur', 'dura',
            'pend', 'trib', 'sens', 'homo', 'ambi', 'cosm', 'form', 'metr', 'mono', 'coll', 'tera', 'patr', 'nasc',
            'fluc', 'over', 'allo', 'vent', 'main', 'cent', 'mand', 'tors', 'path', 'fila', 'derm', 'sanc', 'neur',
            'sign', 'solv', 'sess', 'verv', 'arch', 'phil', 'veri', 'tort', 'corp', 'meta', 'vivi', 'fals', 'fort',
            'mort', 'mega', 'fact', 'magn', 'test', 'oper', 'valu', 'logo', 'medi', 'quad', 'aero', 'frag', 'terr',
            'phan', 'pass', 'loqu', 'grad', 'stan', 'rupt', 'puls', 'term', 'sent', 'fain', 'gest', 'doct', 'agro',
            'plac', 'gram', 'fide', 'capt', 'demo', 'hypn', 'vita', 'sump', 'ecto', 'theo', 'sect', 'acid', 'ante',
            'sept', 'prim', 'annu', 'germ', 'curs', 'post', 'kilo', 'cogn', 'pens', 'cred', 'dorm', 'dict', 'phot',
            'frai', 'caut', 'sacr', 'audi', 'omni', 'poly', 'miss', 'tens', 'fall', 'somn', 'equi', 'vert', 'crea',
            'para', 'port', 'soph', 'cord', 'mill', 'spir', 'with', 'auto', 'vict', 'peri', 'flex', 'cura', 'fore',
            'fili', 'vect', 'fant', 'deca', 'semi', 'here', 'bene', 'vali', 'astr', 'clam', 'solu', 'levi', 'manu',
            'giga', 'quer', 'acri', 'spec', 'brev', 'agri', 'ment', 'cath', 'dent', 'verb', 'anim', 'cata', 'cort',
            'serv', 'hydra', 'liber', 'fract', 'paleo', 'trans', 'multi', 'simul', 'extra', 'extro', 'feder', 'super',
            'andro', 'sanct', 'belli', 'quest', 'penta', 'punct', 'recti', 'supra', 'domin', 'morph', 'solut', 'simil',
            'phant', 'chrom', 'helio', 'ortho', 'cresc', 'spect', 'meter', 'quint', 'milli', 'signi', 'prime', 'aster',
            'intro', 'tempo', 'ambul', 'chron', 'exter', 'hyper', 'calor', 'femto', 'alter', 'tract', 'gastr', 'psych',
            'intra', 'mania', 'nomin', 'liter', 'photo', 'graph', 'retro', 'migra', 'infra', 'centr', 'labor', 'cyclo',
            'contr', 'nomen', 'numer', 'vicis', 'proto', 'therm', 'junct', 'scrib', 'terra', 'pater', 'juven', 'matri',
            'bibli', 'inter', 'dynam', 'micro', 'oligo', 'feign', 'human', 'hydro', 'capit', 'gloss', 'satis', 'struct',
            'biblio', 'contra', 'gastro', 'pneuma', 'string', 'ultima', 'phobia', 'sphere', 'hetero', 'volcan',
            'strict', 'centri', 'circum', 'numisma', 'pneumon', 'phlegma', 'counter', 'anthrop', 'portion'}